version: '2'
services:
  web:
      depends_on:
      - api
      ports: 
      - 8088:80
      image: smhi-nginx:latest
  api:
    depends_on:
      - database
    image: smhi-api:latest
    entrypoint: ./smhi-api
    environment:
      DATABASE: "host=database dbname=smhi password=never4get user=smhi"
  database:
    image: postgres # smhi-database:latest
    environment:
      POSTGRES_PASSWORD: never4get
      POSTGRES_USER: smhi
