version: '2'
services:
  web:
      depends_on:
      - api
      ports: 
      - 8088:80
      image: smhi-nginx:latest
  api:
    depends_on:
      - database
    image: smhi-api:latest
    entrypoint: ./smhi-api
    environment:
     DB_HOST: database
     DB_PORT: 5432
     DB_NAME: smhi
     DB_USER: smhi
     DB_PASSWORD: never4get
  scraper:
    depends_on:
      - database
    image: smhi-scraper:latest
    entrypoint: ./smhi-scraper
    environment:
     DB_HOST: database
     DB_PORT: 5432
     DB_NAME: smhi
     DB_USER: smhi
     DB_PASSWORD: never4get
  database:
    image: postgres # smhi-database:latest
    environment:
      POSTGRES_PASSWORD: never4get
      POSTGRES_USER: smhi
