name:                smhi
version:             0.1.0.0
github:              "kaffepanna/smhi"
license:             BSD3
author:              "Patrik Pettersson"
maintainer:          "pettersson.pa@gmail.com"
copyright:           "2019 Patrik Pettersson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kaffepanna/smhi#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- aeson 
- bytestring
- http-client
- vector
- extra
- sqlite-simple
- mtl
- co-log >= 0.3
- interpolatedstring-perl6
- statistics
- filepath
- beam

library:
  source-dirs: src

executables:
  smhi-graph:
    main:                Main.hs
    source-dirs:         graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smhi
    - Chart
    - Chart-diagrams
  smhi-scraper:
    main:                Main.hs
    source-dirs:         scraper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smhi

tests:
  smhi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smhi
