apiVersion: v1
kind: Service
metadata:
  name: smhi-api
  labels:
    app: smhi
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: smhi
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smhi-api
  labels:
    app: smhi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smhi
      tier: backend
  template:
    metadata:
      name: smhi-api
      labels:
        app: smhi
        tier: backend
    spec:
      containers:
        - name: api
          image: "eu.gcr.io/smhi-285408/smhi-api@sha256:fc56e47e4fb000fd1f6badeec3e48c7a9adbcdc6d165e2f116091af359cea95e"
          env:
            - name: DB_HOST
              value: "smhi-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "db-user"
                  key: "username"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "db-user"
                  key: "password"
          ports:
            - containerPort: 3000 
